# Generated by Django 4.0.1 on 2022-01-16 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(max_length=256, verbose_name='Facebook')),
                ('website', models.URLField(max_length=256, verbose_name='Website')),
                ('twitter', models.URLField(max_length=256, verbose_name='Twitter')),
                ('instagram', models.URLField(max_length=256, verbose_name='Instagram')),
                ('youtube', models.URLField(max_length=256, verbose_name='Youtube')),
                ('github', models.URLField(max_length=256, verbose_name='Github')),
                ('main_link', models.URLField(max_length=256, verbose_name='Main link')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small', models.URLField(max_length=1024, verbose_name='Малое фото')),
                ('large', models.URLField(max_length=1024, verbose_name='Большое фото')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=256, verbose_name='Полное имя')),
                ('about_me', models.CharField(max_length=256, verbose_name='Обо мне')),
                ('looking_for_a_job', models.BooleanField(default=False, verbose_name='Ищу ли работу')),
                ('looking_for_a_job_description', models.CharField(max_length=512, verbose_name='Описание поиска работы')),
                ('contacts', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.contact')),
                ('photos', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.photo')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.user')),
            ],
        ),
    ]
