# Generated by Django 4.0.1 on 2022-04-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_remove_photo_large_remove_photo_small_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img_file',
            field=models.ImageField(blank=True, upload_to='avatars/ava', verbose_name='файл аватарки'),
        ),
    ]
