# Generated by Django 4.0.1 on 2022-01-18 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_remove_profile_contacts_remove_profile_photos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.profile'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.profile'),
        ),
    ]
