# Generated by Django 4.0.1 on 2022-02-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_user_options_user_img_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friends', to='mainapp.Profile'),
        ),
    ]
