# Generated by Django 4.0.1 on 2022-02-22 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_alter_message_recipient_alter_message_sender'),
    ]

    operations = [
        migrations.RenameModel('Message', 'Dialog'),
    ]
