# Generated by Django 4.0.1 on 2022-02-22 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_dialog_alter_user_options_alter_user_managers_and_more'),
        ('mainapp', '0012_dialog_alter_profile_friends_message'),
        ('mainapp', '0012_dialog_alter_profile_friends_post_message'),
        ('mainapp', '0013_alter_message_recipient_alter_message_sender_dialog_and_more'),
        ('mainapp', '0014_auto_20220222_0700'),
        ('mainapp', '0016_rename_messages_dialog_alter_dialog_options_and_more'),
    ]

    operations = [
    ]
